version: '3.7'

services:
  # ==============================================
  # Laravel Application Containers
  # ==============================================

  # Apache / PHP
  web:
    image: webwhales/for-laravel-apache:php7.0
    container_name: web
    hostname: domain.localhost
    restart: unless-stopped
    volumes:
      - ./.docker/conf/apache-site.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/conf/php-site.ini:/usr/local/etc/php/conf.d/site.ini
      - ./.docker/conf/supervisor-site.conf:/etc/supervisor/conf.d/site.conf
      - ./.docker/logs/apache:/var/log/apache2
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    links:
      - db

  # MySQL
  db:
    image: mariadb:10.4
    container_name: db
    restart: unless-stopped
    volumes:
      - ./.docker/conf/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
      - ./.docker/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "KxxLtk8GoI0Fx7JkCWBDZQGW9CPFJjC1"
      MYSQL_DATABASE: "laravel_db"
      MYSQL_USER: "laravel_db_user"
      MYSQL_PASSWORD: "laravel_db_pass"
    command: mysqld --sql_mode="" --init-file=/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "3306:3306"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: domain-pma.localhost
    restart: unless-stopped
    volumes:
      - ./.docker/conf/phpmyadmin-config.php:/etc/phpmyadmin/config.user.inc.php
      - ./.docker/data/phpmyadmin/sessions:/sessions
      - ./.docker/data/phpmyadmin/uploads:/var/uploads
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: "1"
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "KxxLtk8GoI0Fx7JkCWBDZQGW9CPFJjC1"
    links:
      - db


# ==============================================
# Volumes
# ==============================================
volumes:
  db_volume: